## Append samples of your project ##
resources:
- agent_v1alpha1_agentruntime_basic.yaml
- agent_v1alpha1_agentruntime_full.yaml
- agent_v1alpha1_agentruntime_tool.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
