kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .DSCI.Spec.ApplicationNamespace }}
  namespace: {{ .DSCI.Spec.ApplicationNamespace }}
spec:
  podSelector: {}
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            opendatahub.io/generated-namespace: 'true'
    - from:
      - namespaceSelector:
          matchLabels:
            opendatahub.io/application-namespace: 'true'
    - from:
      - namespaceSelector:
          matchLabels:
            network.openshift.io/policy-group: ingress
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: openshift-host-network
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: openshift-monitoring
  policyTypes:
    - Ingress*