apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../after
  - ../pre-processing
  - envoy-filter.yaml
  - plugins-configmap.yaml

images:
  - name: payload-processing
    newName: quay.io/opendatahub/odh-ai-gateway-payload-processing
    newTag: 36614760abfa1b3fb2b521a89097bdaf6e0693b5
