apiVersion: v1
kind: ConfigMap
metadata:
  name: payload-processing-plugins
  namespace: openshift-ingress
data:
  custom-pre-processing-ipp-config.yaml: |
    apiVersion: llm-d.ai/v1alpha1
    kind: PayloadProcessorConfig
    plugins:
    - type: body-field-to-header
      name: model-extractor
      parameters:
        fieldName: model
        headerName: X-Gateway-Model-Name
    profiles:
    - name: default
      plugins:
        request:
        - pluginRef: model-extractor
  custom-ipp-config.yaml: |
    apiVersion: llm-d.ai/v1alpha1
    kind: PayloadProcessorConfig
    plugins:
    - type: model-provider-resolver
    - type: api-translation
    - type: apikey-injection
    profiles:
    - name: default
      plugins:
        request:
        - pluginRef: model-provider-resolver
        - pluginRef: api-translation
        - pluginRef: apikey-injection
        response:
        - pluginRef: api-translation
