apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: maas-api-metrics
  labels:
    app.opendatahub.io/modelsasservice: "true"
    app.kubernetes.io/part-of: maas
    app.kubernetes.io/component: monitoring
    monitoring.opendatahub.io/scrape: "true"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: maas-api
  podMetricsEndpoints:
  - port: metrics
    path: /metrics
    interval: 30s
