apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: workload-variant-autoscaler
  name: variantautoscaling-viewer-role
rules:
- apiGroups:
  - llmd.ai
  resources:
  - variantautoscalings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - llmd.ai
  resources:
  - variantautoscalings/status
  verbs:
  - get
