//go:build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/opendatahub-io/opendatahub-operator/v2/apis/infrastructure/v1"
	conditionsv1 "github.com/openshift/custom-resource-status/conditions/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCCodeFlare) DeepCopyInto(out *DSCCodeFlare) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCCodeFlare.
func (in *DSCCodeFlare) DeepCopy() *DSCCodeFlare {
	if in == nil {
		return nil
	}
	out := new(DSCCodeFlare)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DSCCodeFlare) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCCodeFlareSpec) DeepCopyInto(out *DSCCodeFlareSpec) {
	*out = *in
	in.DSCComponentSpec.DeepCopyInto(&out.DSCComponentSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCCodeFlareSpec.
func (in *DSCCodeFlareSpec) DeepCopy() *DSCCodeFlareSpec {
	if in == nil {
		return nil
	}
	out := new(DSCCodeFlareSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCCodeFlareStatus) DeepCopyInto(out *DSCCodeFlareStatus) {
	*out = *in
	in.DSCComponentStatus.DeepCopyInto(&out.DSCComponentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCCodeFlareStatus.
func (in *DSCCodeFlareStatus) DeepCopy() *DSCCodeFlareStatus {
	if in == nil {
		return nil
	}
	out := new(DSCCodeFlareStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCComponentSpec) DeepCopyInto(out *DSCComponentSpec) {
	*out = *in
	if in.ServiceMesh != nil {
		in, out := &in.ServiceMesh, &out.ServiceMesh
		*out = new(v1.ServiceMeshSpec)
		(*in).DeepCopyInto(*out)
	}
	out.Monitoring = in.Monitoring
	in.ComponentDevFlags.DeepCopyInto(&out.ComponentDevFlags)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCComponentSpec.
func (in *DSCComponentSpec) DeepCopy() *DSCComponentSpec {
	if in == nil {
		return nil
	}
	out := new(DSCComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCComponentStatus) DeepCopyInto(out *DSCComponentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]conditionsv1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCComponentStatus.
func (in *DSCComponentStatus) DeepCopy() *DSCComponentStatus {
	if in == nil {
		return nil
	}
	out := new(DSCComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCDashboard) DeepCopyInto(out *DSCDashboard) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCDashboard.
func (in *DSCDashboard) DeepCopy() *DSCDashboard {
	if in == nil {
		return nil
	}
	out := new(DSCDashboard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DSCDashboard) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCDataSciencePipeline) DeepCopyInto(out *DSCDataSciencePipeline) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCDataSciencePipeline.
func (in *DSCDataSciencePipeline) DeepCopy() *DSCDataSciencePipeline {
	if in == nil {
		return nil
	}
	out := new(DSCDataSciencePipeline)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DSCDataSciencePipeline) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCDataSciencePipelineSpec) DeepCopyInto(out *DSCDataSciencePipelineSpec) {
	*out = *in
	in.DSCComponentSpec.DeepCopyInto(&out.DSCComponentSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCDataSciencePipelineSpec.
func (in *DSCDataSciencePipelineSpec) DeepCopy() *DSCDataSciencePipelineSpec {
	if in == nil {
		return nil
	}
	out := new(DSCDataSciencePipelineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCDataSciencePipelinetatus) DeepCopyInto(out *DSCDataSciencePipelinetatus) {
	*out = *in
	in.DSCComponentStatus.DeepCopyInto(&out.DSCComponentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCDataSciencePipelinetatus.
func (in *DSCDataSciencePipelinetatus) DeepCopy() *DSCDataSciencePipelinetatus {
	if in == nil {
		return nil
	}
	out := new(DSCDataSciencePipelinetatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCDevFlags) DeepCopyInto(out *DSCDevFlags) {
	*out = *in
	if in.Manifests != nil {
		in, out := &in.Manifests, &out.Manifests
		*out = make([]ManifestsConfig, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCDevFlags.
func (in *DSCDevFlags) DeepCopy() *DSCDevFlags {
	if in == nil {
		return nil
	}
	out := new(DSCDevFlags)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCKserve) DeepCopyInto(out *DSCKserve) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCKserve.
func (in *DSCKserve) DeepCopy() *DSCKserve {
	if in == nil {
		return nil
	}
	out := new(DSCKserve)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DSCKserve) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCKueue) DeepCopyInto(out *DSCKueue) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCKueue.
func (in *DSCKueue) DeepCopy() *DSCKueue {
	if in == nil {
		return nil
	}
	out := new(DSCKueue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DSCKueue) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCModelMeshServing) DeepCopyInto(out *DSCModelMeshServing) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCModelMeshServing.
func (in *DSCModelMeshServing) DeepCopy() *DSCModelMeshServing {
	if in == nil {
		return nil
	}
	out := new(DSCModelMeshServing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DSCModelMeshServing) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCModelReg) DeepCopyInto(out *DSCModelReg) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCModelReg.
func (in *DSCModelReg) DeepCopy() *DSCModelReg {
	if in == nil {
		return nil
	}
	out := new(DSCModelReg)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DSCModelReg) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCRay) DeepCopyInto(out *DSCRay) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCRay.
func (in *DSCRay) DeepCopy() *DSCRay {
	if in == nil {
		return nil
	}
	out := new(DSCRay)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DSCRay) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCTO) DeepCopyInto(out *DSCTO) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCTO.
func (in *DSCTO) DeepCopy() *DSCTO {
	if in == nil {
		return nil
	}
	out := new(DSCTO)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DSCTO) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCTrustyAI) DeepCopyInto(out *DSCTrustyAI) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCTrustyAI.
func (in *DSCTrustyAI) DeepCopy() *DSCTrustyAI {
	if in == nil {
		return nil
	}
	out := new(DSCTrustyAI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DSCTrustyAI) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DSCWorkbench) DeepCopyInto(out *DSCWorkbench) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DSCWorkbench.
func (in *DSCWorkbench) DeepCopy() *DSCWorkbench {
	if in == nil {
		return nil
	}
	out := new(DSCWorkbench)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DSCWorkbench) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardComponentSpec) DeepCopyInto(out *DashboardComponentSpec) {
	*out = *in
	in.DSCComponentSpec.DeepCopyInto(&out.DSCComponentSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardComponentSpec.
func (in *DashboardComponentSpec) DeepCopy() *DashboardComponentSpec {
	if in == nil {
		return nil
	}
	out := new(DashboardComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardComponentStatus) DeepCopyInto(out *DashboardComponentStatus) {
	*out = *in
	in.DSCComponentStatus.DeepCopyInto(&out.DSCComponentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardComponentStatus.
func (in *DashboardComponentStatus) DeepCopy() *DashboardComponentStatus {
	if in == nil {
		return nil
	}
	out := new(DashboardComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevFlags) DeepCopyInto(out *DevFlags) {
	*out = *in
	in.DSCDevFlags.DeepCopyInto(&out.DSCDevFlags)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevFlags.
func (in *DevFlags) DeepCopy() *DevFlags {
	if in == nil {
		return nil
	}
	out := new(DevFlags)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KFTOComponentSpec) DeepCopyInto(out *KFTOComponentSpec) {
	*out = *in
	in.DSCComponentSpec.DeepCopyInto(&out.DSCComponentSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KFTOComponentSpec.
func (in *KFTOComponentSpec) DeepCopy() *KFTOComponentSpec {
	if in == nil {
		return nil
	}
	out := new(KFTOComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KFTOComponentStatus) DeepCopyInto(out *KFTOComponentStatus) {
	*out = *in
	in.DSCComponentStatus.DeepCopyInto(&out.DSCComponentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KFTOComponentStatus.
func (in *KFTOComponentStatus) DeepCopy() *KFTOComponentStatus {
	if in == nil {
		return nil
	}
	out := new(KFTOComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KserveComponentSpec) DeepCopyInto(out *KserveComponentSpec) {
	*out = *in
	in.DSCComponentSpec.DeepCopyInto(&out.DSCComponentSpec)
	out.Serving = in.Serving
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KserveComponentSpec.
func (in *KserveComponentSpec) DeepCopy() *KserveComponentSpec {
	if in == nil {
		return nil
	}
	out := new(KserveComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KserveComponentStatus) DeepCopyInto(out *KserveComponentStatus) {
	*out = *in
	in.DSCComponentStatus.DeepCopyInto(&out.DSCComponentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KserveComponentStatus.
func (in *KserveComponentStatus) DeepCopy() *KserveComponentStatus {
	if in == nil {
		return nil
	}
	out := new(KserveComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KueueComponentSpec) DeepCopyInto(out *KueueComponentSpec) {
	*out = *in
	in.DSCComponentSpec.DeepCopyInto(&out.DSCComponentSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KueueComponentSpec.
func (in *KueueComponentSpec) DeepCopy() *KueueComponentSpec {
	if in == nil {
		return nil
	}
	out := new(KueueComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KueueComponentStatus) DeepCopyInto(out *KueueComponentStatus) {
	*out = *in
	in.DSCComponentStatus.DeepCopyInto(&out.DSCComponentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KueueComponentStatus.
func (in *KueueComponentStatus) DeepCopy() *KueueComponentStatus {
	if in == nil {
		return nil
	}
	out := new(KueueComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManifestsConfig) DeepCopyInto(out *ManifestsConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManifestsConfig.
func (in *ManifestsConfig) DeepCopy() *ManifestsConfig {
	if in == nil {
		return nil
	}
	out := new(ManifestsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelMeshServingComponentSpec) DeepCopyInto(out *ModelMeshServingComponentSpec) {
	*out = *in
	in.DSCComponentSpec.DeepCopyInto(&out.DSCComponentSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelMeshServingComponentSpec.
func (in *ModelMeshServingComponentSpec) DeepCopy() *ModelMeshServingComponentSpec {
	if in == nil {
		return nil
	}
	out := new(ModelMeshServingComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelMeshServingComponentStatus) DeepCopyInto(out *ModelMeshServingComponentStatus) {
	*out = *in
	in.DSCComponentStatus.DeepCopyInto(&out.DSCComponentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelMeshServingComponentStatus.
func (in *ModelMeshServingComponentStatus) DeepCopy() *ModelMeshServingComponentStatus {
	if in == nil {
		return nil
	}
	out := new(ModelMeshServingComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRegComponentSpec) DeepCopyInto(out *ModelRegComponentSpec) {
	*out = *in
	in.DSCComponentSpec.DeepCopyInto(&out.DSCComponentSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRegComponentSpec.
func (in *ModelRegComponentSpec) DeepCopy() *ModelRegComponentSpec {
	if in == nil {
		return nil
	}
	out := new(ModelRegComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelRegComponentStatus) DeepCopyInto(out *ModelRegComponentStatus) {
	*out = *in
	in.DSCComponentStatus.DeepCopyInto(&out.DSCComponentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelRegComponentStatus.
func (in *ModelRegComponentStatus) DeepCopy() *ModelRegComponentStatus {
	if in == nil {
		return nil
	}
	out := new(ModelRegComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RayComponentSpec) DeepCopyInto(out *RayComponentSpec) {
	*out = *in
	in.DSCComponentSpec.DeepCopyInto(&out.DSCComponentSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RayComponentSpec.
func (in *RayComponentSpec) DeepCopy() *RayComponentSpec {
	if in == nil {
		return nil
	}
	out := new(RayComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RayComponentStatus) DeepCopyInto(out *RayComponentStatus) {
	*out = *in
	in.DSCComponentStatus.DeepCopyInto(&out.DSCComponentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RayComponentStatus.
func (in *RayComponentStatus) DeepCopy() *RayComponentStatus {
	if in == nil {
		return nil
	}
	out := new(RayComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustyAIComponentSpec) DeepCopyInto(out *TrustyAIComponentSpec) {
	*out = *in
	in.DSCComponentSpec.DeepCopyInto(&out.DSCComponentSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustyAIComponentSpec.
func (in *TrustyAIComponentSpec) DeepCopy() *TrustyAIComponentSpec {
	if in == nil {
		return nil
	}
	out := new(TrustyAIComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustyAIComponentStatus) DeepCopyInto(out *TrustyAIComponentStatus) {
	*out = *in
	in.DSCComponentStatus.DeepCopyInto(&out.DSCComponentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustyAIComponentStatus.
func (in *TrustyAIComponentStatus) DeepCopy() *TrustyAIComponentStatus {
	if in == nil {
		return nil
	}
	out := new(TrustyAIComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBComponentSpec) DeepCopyInto(out *WBComponentSpec) {
	*out = *in
	in.DSCComponentSpec.DeepCopyInto(&out.DSCComponentSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBComponentSpec.
func (in *WBComponentSpec) DeepCopy() *WBComponentSpec {
	if in == nil {
		return nil
	}
	out := new(WBComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WBComponentStatus) DeepCopyInto(out *WBComponentStatus) {
	*out = *in
	in.DSCComponentStatus.DeepCopyInto(&out.DSCComponentStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WBComponentStatus.
func (in *WBComponentStatus) DeepCopy() *WBComponentStatus {
	if in == nil {
		return nil
	}
	out := new(WBComponentStatus)
	in.DeepCopyInto(out)
	return out
}
