apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - path: deployment-tls-patch.yaml
    target:
      kind: Deployment
      name: seaweedfs
  - path: init-job-tls-patch.yaml
    target:
      kind: Job
      name: init-seaweedfs
  - path: service-tls-patch.yaml
    target:
      kind: Service
      name: minio-service
  - path: networkpolicy-tls-patch.yaml
    target:
      kind: NetworkPolicy
      name: seaweedfs
