---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - get
  - update
- apiGroups:
  - agent.kagenti.dev
  resources:
  - agentcards
  - agentruntimes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agent.kagenti.dev
  resources:
  - agentcards/finalizers
  - agentruntimes/finalizers
  verbs:
  - update
- apiGroups:
  - agent.kagenti.dev
  resources:
  - agentcards/status
  - agentruntimes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - agents.x-k8s.io
  resources:
  - sandboxes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agents.x-k8s.io
  resources:
  - sandboxes/finalizers
  verbs:
  - update
- apiGroups:
  - agents.x-k8s.io
  resources:
  - sandboxes/scale
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/finalizers
  - statefulsets/finalizers
  verbs:
  - update
- apiGroups:
  - mlflow.opendatahub.io
  resources:
  - mlflowexperiments
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - mlflow.opendatahub.io
  resources:
  - mlflows
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.tekton.dev
  resources:
  - tektonconfigs
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - get
  - list
  - update
  - watch
